### ISSUE TITLE
Zou het ook mogelijk zijn om een API aan te bieden voor authenticatie?

### ISSUE THREAD

**Issue by mborsten** [D66hackathon/D66-Data-API-Server#1]
Als er een API is voor authenticatie, zouden we D66 leden kunnen authenticeren vanuit andere applicaties. Of valt dit niet binnen de scope van dit project?

**Comment by BramFokke** [comment]
Dat is zeker een goed idee, maar het valt niet binnen de scope van deze API. Roy van der Linden van D66 Amsterdam is wel bezig met een authenticatie API.

**Comment by mborsten** [comment]
Cool, dan ga ik met hem contact opnemen.

**Comment by vindia** [comment]
Dat is overigens wel vooral vanuit Amsterdam, hoewel het mogelijk is uit te breiden naar een breder perspectief. Maar ik zou authenticatie wel vanuit "landelijk" benaderen. 

Die wens is er overigens wel sterk en er wordt gewerkt aan een API vanuit de ledenadministratie, maar daar zit authenticatie niet direct in.
